name: Email Step Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: 23f2004492@ds.study.iitm.ac.in
        run: echo "This step contains the required email address"
        
      - name: Verify files
        run: |
          ls -la
          echo "Checking repository files"
